# AI Classification System Configuration
# Optimized for: HR position classification using ChatGPT
# Target: Classify position_name_english into predefined categories

#######################
# File paths and basics
#######################
input_file: "input/HR_monthly_panel_translated.dta"
output_file: "output/HR_monthly_panel_classified.dta"
results_dir: "output/classification_results"

# Text columns to classify
text_columns:
  - position_name_english

#######################
# Text Preprocessing
#######################
preprocessing:
  lowercase: true
  remove_punctuation: false      # Keep punctuation for job titles
  remove_stopwords: false        # Keep all words for context
  lemmatize: false
  custom_stopwords: []
  min_word_length: 1
  max_length: 10000

#######################
# Classification Perspectives
#######################
clustering_perspectives:
  # ChatGPT-powered HR position classification
  hr_position_classifier:
    type: "openai_classification"
    columns: 
      - position_name_english
    target_categories:
      - "Executive & Senior Management"
      - "Legal, Compliance & Risk"
      - "Human Resources (HR)"
      - "Administrative Support"
      - "Information Technology (IT)"
      - "Operations & Manufacturing"
      - "Supply Chain & Logistics"
      - "Marketing & Communications"
      - "Sales & Business Development"
      - "Research & Development (R&D)"
      - "Finance & Accounting"
      - "Customer Service & Support"
      - "Engineering"
      - "Healthcare & Medical"
      - "Education & Training"
      - "Consulting & Advisory"
      - "Other/Unknown"
    output_column: "position_category_gpt"
    
    # OpenAI Configuration
    llm_config:
      provider: "openai"
      model: "gpt-3.5-turbo-0125"  # Cost-effective and reliable
      temperature: 0.1             # Very low for consistency
      max_tokens: 50               # Allow slightly more tokens
      timeout: 30
      max_retries: 3
      backoff_factor: 2
      api_key_env: "OPENAI_API_KEY"
    
    # Classification settings
    classification_config:
      unknown_category: "Other/Unknown"
      batch_size: 20               # Reasonable batch size
      include_unknown_in_categories: true
      prompt_template: |
        You are an expert HR classifier. Classify this job position title into exactly ONE category from the list below.
        
        CATEGORIES:
        - Executive & Senior Management
        - Legal, Compliance & Risk
        - Human Resources (HR)
        - Administrative Support
        - Information Technology (IT)
        - Operations & Manufacturing
        - Supply Chain & Logistics
        - Marketing & Communications
        - Sales & Business Development
        - Research & Development (R&D)
        - Finance & Accounting
        - Customer Service & Support
        - Engineering
        - Healthcare & Medical
        - Education & Training
        - Consulting & Advisory
        - Other/Unknown
        
        Job Position: "{text}"
        
        Instructions:
        - Respond with ONLY the exact category name
        - If uncertain or doesn't fit clearly, use "Other/Unknown"
        - Consider the main function of the role
        
        Category:
    
    # Validation settings
    validation:
      strict_category_matching: true
      fallback_strategy: "unknown"

#######################
# AI Classification Global Settings
#######################
ai_classification:
  # Cost management
  cost_management:
    max_cost_per_run: 100.0       # Increased limit for large dataset
    track_token_usage: true
    cost_alerts: true
  
  # Intelligent caching to save costs
  caching:
    enabled: true
    cache_duration_days: 90       # Long cache for job titles
    cache_directory: "ai_cache"
    
  # Rate limiting (optimized for GPT-3.5)
  rate_limiting:
    requests_per_minute: 100      # Conservative rate
    batch_delay_seconds: 1.0      # Gentle on API
    
  # Monitoring
  monitoring:
    log_api_calls: true
    save_raw_responses: false     # Save space
    track_classification_accuracy: true

#######################
# Cluster Labeling (for traditional clustering - not used for AI classification)
#######################
cluster_labeling:
  method: "tfidf"  # This won't be used for AI classification but needed for validation

#######################
# Evaluation Settings
#######################
evaluation:
  metrics:
    - "distribution_analysis"
    - "cost_analysis"
  visualizations:
    - "distribution_plot"
    - "category_breakdown"
  output_format:
    - "html"
    - "csv"
    - "json"

#######################
# Feature Extraction (not needed for AI classification but required for validation)
#######################
feature_extraction:
  method: 'embedding'  # Not used for AI classification but required for config validation
  embedding:
    model: 'sentence-transformers'
    sentence_transformers:
      model_name: 'all-MiniLM-L6-v2'

#######################
# Performance Settings
#######################
performance:
  batch_size: 256
  parallel_jobs: -1              # Use available cores
  cache_embeddings: false        # Not needed for classification
  cache_directory: "cache"
  sample_rate: 1.0               # Process all data

#######################
# Spark Configuration (Minimal - only needed if traditional clustering is used)
#######################
spark:
  executor_memory: "4g"          # Reduced since AI classification doesn't need much memory
  driver_memory: "2g"            # Reduced 
  executor_cores: 2
  default_parallelism: 4

#######################
# Checkpointing
#######################
checkpoint:
  enabled: true
  interval: 1
  directory: "checkpoints"
  max_checkpoints: 3

#######################
# Logging
#######################
logging:
  level: "INFO"
  log_file: "logs/hr_classification.log"
  console_output: true

#######################
# Miscellaneous options
#######################
options:
  seed: 42
  save_intermediate: true
  clean_intermediate_on_success: false